/**
 * QCM banks imported from the "QCM UMMTO classés par cours" PDFs
 * (1re année médecine, 2023-2024). The JSON files are generated by
 * `scripts/import-qcm/parse_ummto_pdf.py` — edit the parser, not the JSON.
 *
 * Questions that could not be published safely (no corrigé type, needs a
 * diagram, ambiguous key…) are kept as drafts: they go to the database for a
 * moderator to fix, but students never see them.
 */
import { createHash } from 'node:crypto';

import { CURRICULUM } from '@/content/curriculum';
import type { SampleQcm } from '@/content/sample-qcms';
import { OPTION_LABELS, type OptionLabel, type QcmType } from '@/types/domain';

import anatomieS2 from './ummto-2023-24/anatomie-s2.json';
import embryologie from './ummto-2023-24/embryologie.json';
import embryologieExplanations from './ummto-2023-24/explanations/embryologie.json';
import histologie from './ummto-2023-24/histologie.json';
import physiologie from './ummto-2023-24/physiologie.json';

export type ImportIssue =
  | 'no_key'
  | 'needs_image'
  | 'ambiguous_key'
  | 'open_question'
  | 'too_few_options'
  | 'bad_option_labels'
  | 'key_not_in_options';

interface ImportedQuestion {
  course: string;
  section: string;
  label: string | null;
  examYear: number | null;
  page: number;
  n: number;
  type: string;
  stem: string;
  options: Array<{ label: string; body: string }>;
  key: string | null;
  rawKey: string | null;
  status: string;
  issues: string[];
}

interface ImportedFile {
  module: string;
  source: string;
  courses: Array<{ slug: string; title: string }>;
  questions: ImportedQuestion[];
}

const FILES: ImportedFile[] = [embryologie, anatomieS2, histologie, physiologie];

/**
 * AI-written explanations, keyed by question id: why each proposition is right
 * or wrong. Grading always follows the corrigé type; when the AI thinks the
 * printed key is wrong, `aiKey` + `keyIssue` show a warning to the student:
 * « le corrigé type retient X, mais la bonne réponse est Y, parce que… ».
 */
export interface AiExplanation {
  why: string;
  options: Partial<Record<OptionLabel, string>>;
  keyIssue?: string;
  aiKey?: string;
  /** Set when the question cannot be shown as-is (needs a picture, garbled options…): back to drafts. */
  draft?: string;
}

export const AI_EXPLANATIONS: Record<string, AiExplanation> = { ...embryologieExplanations };

const AI_NOTE = ' (Explication rédigée par IA : signalez la question si vous repérez une erreur.)';

const ISSUE_NOTES: Record<ImportIssue, string> = {
  no_key: 'pas de corrigé type',
  needs_image: 'la question dépend d’un schéma ou d’une autre question',
  ambiguous_key: 'clé ambiguë',
  open_question: 'question ouverte (réponse rédigée)',
  too_few_options: 'moins de deux propositions',
  bad_option_labels: 'lettres des propositions incohérentes',
  key_not_in_options: 'la clé cite une proposition absente',
};

/** Stable UUID (v5 layout) from the question's identity, so re-imports keep ids. */
function stableId(parts: string[]): string {
  const h = createHash('sha1').update(parts.join('␟')).digest('hex');
  const variant = ((parseInt(h[16], 16) & 0x3) | 0x8).toString(16);
  return `${h.slice(0, 8)}-${h.slice(8, 12)}-5${h.slice(13, 16)}-${variant}${h.slice(17, 20)}-${h.slice(20, 32)}`;
}

function draftNote(q: ImportedQuestion): string {
  const reasons = q.issues.map((i) => ISSUE_NOTES[i as ImportIssue] ?? i).join(' ; ');
  const key = q.rawKey ? ` Clé d’origine : « ${q.rawKey} ».` : '';
  return `[À revoir avant publication — ${reasons}.]${key} Source : p. ${q.page}, question ${q.n}.`;
}

function toSampleQcm(file: ImportedFile, q: ImportedQuestion): SampleQcm {
  const [major, year, code] = file.module.split('/');
  const mod = CURRICULUM.find((m) => m.major === major && m.studyYear === Number(year) && m.code === code);
  if (!mod) throw new Error(`Imported module ${file.module} is not in src/content/curriculum.ts`);
  const course = mod.units.flatMap((u) => u.courses).find((c) => c.slug === q.course);
  if (!course) throw new Error(`Imported course ${file.module}/${q.course} is not in src/content/curriculum.ts`);

  const key = q.key ?? '';
  const id = stableId(['ummto-2023-24', file.module, q.course, q.label ?? '', String(q.n), q.stem, ...q.options.map((o) => o.body)]);
  const ai = AI_EXPLANATIONS[id];
  const status = q.status === 'published' && !ai?.draft ? 'published' : 'draft';
  const warning = ai?.keyIssue
    ? `⚠️ Le corrigé type retient ${[...key].join(', ')}, mais la bonne réponse est ${[...(ai.aiKey ?? '')].join(', ') || 'différente'} : ${ai.keyIssue} `
    : '';
  const explanation =
    status === 'draft'
      ? [ai?.draft ? `[À revoir avant publication — ${ai.draft}]` : draftNote(q), ai?.why].filter(Boolean).join(' ')
      : ai
        ? warning + ai.why + AI_NOTE
        : null;
  return {
    id,
    courseId: course.id,
    moduleId: mod.id,
    type: q.type as QcmType,
    stem: q.stem,
    explanation,
    difficulty: null,
    source: q.label ? `UMMTO · ${q.label}` : 'UMMTO',
    examYear: q.examYear,
    tags: [
      'import:ummto-2023-24',
      ...(ai ? ['explication:ia'] : []),
      ...(ai?.keyIssue ? ['corrige-discutable'] : []),
      ...q.issues.map((i) => `a-revoir:${i}`),
      ...(ai?.draft ? ['a-revoir:signale-par-ia'] : []),
    ],
    status,
    options: q.options
      .filter((o): o is { label: OptionLabel; body: string } => (OPTION_LABELS as readonly string[]).includes(o.label))
      // A draft may repeat a letter (source typo): keep the first so (qcm, label) stays unique.
      .filter((o, i, all) => all.findIndex((x) => x.label === o.label) === i)
      .map((o) => ({ label: o.label, body: o.body, isCorrect: key.includes(o.label), explanation: ai?.options[o.label] ?? null })),
  };
}

export const IMPORTED_QCMS: readonly SampleQcm[] = FILES.flatMap((file) => file.questions.map((q) => toSampleQcm(file, q)));
