/**
 * Starter curriculum — Faculty of Medicine, UMMTO (L1 / L2).
 *
 * Single source of truth for:
 *   - `supabase/seed.sql` (generated by `npm run db:seed:generate`)
 *   - demo mode, when the app runs without a Supabase project
 *
 * ⚠️ The module lists are indicative, based on the national common core for
 * Algerian medical studies. Check them against the official UMMTO programme
 * for the current academic year before going to production; after seeding,
 * edit them in the database (admin tools) rather than here.
 *
 * IDs are explicit and must never be reused: append new entries with new numbers.
 */
import type { LocalizedText, Major, ModuleColor, StudyYear } from '@/types/domain';

export type FixtureKind = 'module' | 'unit' | 'course' | 'qcm';

const KIND_CODE: Record<FixtureKind, number> = { module: 1, unit: 2, course: 3, qcm: 4 };

/** Deterministic, valid UUID for starter content, e.g. module #3 → 00000000-0000-4000-8001-000000000003. */
export function fixtureId(kind: FixtureKind, n: number): string {
  return `00000000-0000-4000-8${String(KIND_CODE[kind]).padStart(3, '0')}-${String(n).padStart(12, '0')}`;
}

export interface CurriculumCourse {
  id: string;
  slug: string;
  title: LocalizedText;
}

export interface CurriculumUnit {
  id: string;
  title: LocalizedText;
  courses: CurriculumCourse[];
}

export interface CurriculumModule {
  id: string;
  major: Major;
  studyYear: StudyYear;
  code: string;
  title: LocalizedText;
  isIntegrated: boolean;
  semester: 1 | 2 | null;
  icon: string;
  color: ModuleColor;
  units: CurriculumUnit[];
}

// --- tiny builders to keep the table below readable --------------------------

const t = (fr: string, en: string): LocalizedText => ({ fr, en });

const course = (n: number, slug: string, title: LocalizedText): CurriculumCourse => ({
  id: fixtureId('course', n),
  slug,
  title,
});

const unit = (n: number, title: LocalizedText, courses: CurriculumCourse[]): CurriculumUnit => ({
  id: fixtureId('unit', n),
  title,
  courses,
});

type ModuleSpec = [
  n: number,
  code: string,
  title: LocalizedText,
  icon: string,
  color: ModuleColor,
  extra?: { isIntegrated?: boolean; semester?: 1 | 2; units?: CurriculumUnit[] },
];

function track(major: Major, studyYear: StudyYear, specs: ModuleSpec[]): CurriculumModule[] {
  return specs.map(([n, code, title, icon, color, extra]) => ({
    id: fixtureId('module', n),
    major,
    studyYear,
    code,
    title,
    icon,
    color,
    isIntegrated: extra?.isIntegrated ?? false,
    semester: extra?.semester ?? null,
    units: extra?.units ?? [],
  }));
}

// --- Médecine ----------------------------------------------------------------

const medicineL1 = track('medicine', 1, [
  [1, 'anatomie', t('Anatomie', 'Anatomy'), 'bone', 'rose', {
    units: [unit(1, t('Ostéologie', 'Osteology'), [
      course(1, 'osteologie-membre-superieur', t('Ostéologie du membre supérieur', 'Upper limb osteology')),
    ])],
  }],
  [2, 'biochimie', t('Biochimie', 'Biochemistry'), 'flask-conical', 'amber', {
    units: [unit(2, t('Biochimie structurale', 'Structural biochemistry'), [
      course(2, 'glucides', t('Les glucides', 'Carbohydrates')),
      course(3, 'acides-amines-peptides', t('Acides aminés et peptides', 'Amino acids and peptides')),
    ])],
  }],
  [3, 'biophysique', t('Biophysique', 'Biophysics'), 'atom', 'sky', {
    units: [unit(3, t('Biophysique des solutions', 'Biophysics of solutions'), [
      course(4, 'grandeurs-unites', t('Grandeurs et unités', 'Quantities and units')),
      course(5, 'solutions-osmose', t('Solutions et osmose', 'Solutions and osmosis')),
    ])],
  }],
  [4, 'biostatistique', t('Biostatistique – Informatique', 'Biostatistics & Computing'), 'chart-column', 'indigo', {
    units: [unit(4, t('Statistique inférentielle', 'Inferential statistics'), [
      course(6, 'loi-normale', t('La loi normale', 'The normal distribution')),
    ])],
  }],
  [5, 'chimie', t('Chimie', 'Chemistry'), 'beaker', 'lime'],
  [6, 'cytologie', t('Cytologie', 'Cell biology'), 'microscope', 'emerald', {
    units: [unit(5, t('La cellule', 'The cell'), [
      course(7, 'membrane-plasmique', t('La membrane plasmique', 'The plasma membrane')),
      course(8, 'organites', t('Les organites cellulaires', 'Cell organelles')),
      course(9, 'cycle-cellulaire', t('Cycle cellulaire et mitose', 'Cell cycle and mitosis')),
    ])],
  }],
  [7, 'embryologie', t('Embryologie', 'Embryology'), 'baby', 'fuchsia', {
    units: [unit(6, t('Embryologie générale', 'General embryology'), [
      course(10, 'fecondation', t('La fécondation', 'Fertilisation')),
    ])],
  }],
  [8, 'histologie', t('Histologie', 'Histology'), 'layers', 'violet', {
    units: [unit(7, t('Tissus épithéliaux', 'Epithelial tissues'), [
      course(11, 'epitheliums-revetement', t('Épithéliums de revêtement', 'Covering epithelia')),
    ])],
  }],
  [9, 'physiologie', t('Physiologie', 'Physiology'), 'activity', 'teal', {
    units: [unit(8, t('Physiologie générale', 'General physiology'), [
      course(12, 'potentiels-membranaires', t('Potentiels membranaires', 'Membrane potentials')),
      course(13, 'regulation-glycemie', t('Régulation de la glycémie', 'Blood glucose regulation')),
    ])],
  }],
  [10, 'ssh', t('Sciences humaines et sociales', 'Humanities & social sciences'), 'users', 'slate'],
]);

const medicineL2 = track('medicine', 2, [
  [11, 'uei-cardio-respiratoire', t('Appareil cardio-vasculaire et respiratoire', 'Cardiovascular & respiratory system'), 'heart-pulse', 'rose', {
    isIntegrated: true,
    units: [
      unit(9, t('Anatomie', 'Anatomy'), [course(14, 'coeur', t('Le cœur', 'The heart'))]),
      unit(10, t('Physiologie', 'Physiology'), [
        course(15, 'debit-cardiaque', t('Le débit cardiaque', 'Cardiac output')),
        course(16, 'mecanique-ventilatoire', t('Mécanique ventilatoire', 'Respiratory mechanics')),
      ]),
    ],
  }],
  [12, 'uei-digestif', t('Appareil digestif', 'Digestive system'), 'apple', 'orange', {
    isIntegrated: true,
    units: [unit(11, t('Histologie – Physiologie', 'Histology – Physiology'), [
      course(17, 'estomac', t("L'estomac", 'The stomach')),
    ])],
  }],
  [13, 'uei-urinaire', t('Appareil urinaire', 'Urinary system'), 'droplets', 'sky', { isIntegrated: true }],
  [14, 'uei-endocrinien', t('Appareil endocrinien et de la reproduction', 'Endocrine & reproductive system'), 'flask-round', 'fuchsia', { isIntegrated: true }],
  [15, 'uei-neuro', t('Système nerveux et organes des sens', 'Nervous system & sense organs'), 'brain', 'violet', { isIntegrated: true }],
  [16, 'immunologie', t('Immunologie', 'Immunology'), 'shield', 'emerald', {
    units: [unit(12, t('Immunologie fondamentale', 'Basic immunology'), [
      course(18, 'immunoglobulines', t('Les immunoglobulines', 'Immunoglobulins')),
    ])],
  }],
  [17, 'genetique', t('Génétique', 'Genetics'), 'dna', 'indigo', {
    units: [unit(13, t('Cytogénétique', 'Cytogenetics'), [
      course(19, 'caryotype', t('Le caryotype humain', 'The human karyotype')),
    ])],
  }],
  [18, 'ssh', t('Sciences humaines et sociales', 'Humanities & social sciences'), 'users', 'slate'],
]);

// --- Chirurgie dentaire ------------------------------------------------------

const dentistryL1 = track('dentistry', 1, [
  [19, 'anatomie', t('Anatomie générale', 'General anatomy'), 'bone', 'rose'],
  [20, 'anatomie-dentaire', t('Anatomie dentaire', 'Dental anatomy'), 'tooth', 'cyan', {
    units: [unit(14, t('Morphologie dentaire', 'Dental morphology'), [
      course(20, 'formule-dentaire', t('Formule dentaire', 'Dental formula')),
      course(21, 'tissus-dentaires', t('Les tissus dentaires', 'Dental tissues')),
    ])],
  }],
  [21, 'biochimie', t('Biochimie', 'Biochemistry'), 'flask-conical', 'amber'],
  [22, 'biophysique', t('Biophysique', 'Biophysics'), 'atom', 'sky'],
  [23, 'chimie', t('Chimie', 'Chemistry'), 'beaker', 'lime'],
  [24, 'cytologie', t('Cytologie', 'Cell biology'), 'microscope', 'emerald', {
    units: [unit(15, t('La cellule', 'The cell'), [
      course(22, 'organites', t('Les organites cellulaires', 'Cell organelles')),
    ])],
  }],
  [25, 'embryologie', t('Embryologie', 'Embryology'), 'baby', 'fuchsia'],
  [26, 'histologie', t('Histologie', 'Histology'), 'layers', 'violet'],
  [27, 'physiologie', t('Physiologie', 'Physiology'), 'activity', 'teal'],
  [28, 'biostatistique', t('Biostatistique', 'Biostatistics'), 'chart-column', 'indigo'],
  [29, 'ssh', t('Sciences humaines et sociales', 'Humanities & social sciences'), 'users', 'slate'],
]);

const dentistryL2 = track('dentistry', 2, [
  [30, 'anatomie-tete-cou', t('Anatomie tête et cou', 'Head & neck anatomy'), 'skull', 'rose', {
    units: [unit(16, t('Myologie et innervation', 'Muscles and innervation'), [
      course(23, 'muscles-masticateurs', t('Les muscles masticateurs', 'Masticatory muscles')),
      course(24, 'innervation-dentaire', t('Innervation dentaire', 'Dental innervation')),
    ])],
  }],
  [31, 'histo-embryo-bucco-dentaire', t('Histologie-embryologie bucco-dentaire', 'Oral histology & embryology'), 'layers', 'violet', {
    units: [unit(17, t('Tissus durs de la dent', 'Dental hard tissues'), [
      course(25, 'dentine', t('La dentine', 'Dentin')),
    ])],
  }],
  [32, 'physiologie', t('Physiologie', 'Physiology'), 'activity', 'teal'],
  [33, 'biochimie', t('Biochimie', 'Biochemistry'), 'flask-conical', 'amber'],
  [34, 'microbiologie', t('Microbiologie', 'Microbiology'), 'bug', 'lime'],
  [35, 'immunologie', t('Immunologie', 'Immunology'), 'shield', 'emerald'],
  [36, 'biomateriaux', t('Biomatériaux dentaires', 'Dental materials'), 'gem', 'sky'],
  [37, 'odontologie-conservatrice', t('Odontologie conservatrice (préclinique)', 'Operative dentistry (preclinical)'), 'tooth', 'cyan'],
  [38, 'prothese', t('Prothèse (initiation)', 'Prosthodontics (introduction)'), 'smile', 'orange'],
]);

// --- Pharmacie ---------------------------------------------------------------

const pharmacyL1 = track('pharmacy', 1, [
  [39, 'chimie-generale', t('Chimie générale et minérale', 'General & inorganic chemistry'), 'beaker', 'lime', {
    units: [unit(18, t('Atomistique et solutions', 'Atomic structure and solutions'), [
      course(26, 'atome', t("Structure de l'atome", 'Atomic structure')),
      course(27, 'acides-bases', t('Acides et bases', 'Acids and bases')),
    ])],
  }],
  [40, 'chimie-organique', t('Chimie organique', 'Organic chemistry'), 'hexagon', 'orange', {
    units: [unit(19, t('Généralités', 'Fundamentals'), [
      course(28, 'hybridation', t('Hybridation du carbone', 'Carbon hybridisation')),
    ])],
  }],
  [41, 'biophysique', t('Biophysique', 'Biophysics'), 'atom', 'sky'],
  [42, 'mathematiques', t('Mathématiques – Biostatistique', 'Mathematics & biostatistics'), 'sigma', 'indigo'],
  [43, 'biologie-cellulaire', t('Biologie cellulaire', 'Cell biology'), 'microscope', 'emerald'],
  [44, 'botanique', t('Botanique', 'Botany'), 'leaf', 'teal', {
    units: [unit(20, t('Biologie végétale', 'Plant biology'), [
      course(29, 'cellule-vegetale', t('La cellule végétale', 'The plant cell')),
    ])],
  }],
  [45, 'anatomie-physiologie', t('Anatomie – Physiologie', 'Anatomy & physiology'), 'activity', 'rose'],
  [46, 'geologie', t('Géologie', 'Geology'), 'mountain', 'amber'],
  [47, 'ssh', t('Terminologie et sciences humaines', 'Terminology & humanities'), 'users', 'slate'],
]);

const pharmacyL2 = track('pharmacy', 2, [
  [48, 'biochimie', t('Biochimie', 'Biochemistry'), 'flask-conical', 'amber', {
    units: [unit(21, t('Enzymologie', 'Enzymology'), [
      course(30, 'cinetique-enzymatique', t('Cinétique enzymatique', 'Enzyme kinetics')),
    ])],
  }],
  [49, 'chimie-analytique', t('Chimie analytique', 'Analytical chemistry'), 'test-tube', 'cyan', {
    units: [unit(22, t('Méthodes spectrales', 'Spectral methods'), [
      course(31, 'spectrophotometrie', t('Spectrophotométrie UV-visible', 'UV-visible spectrophotometry')),
    ])],
  }],
  [50, 'chimie-organique', t('Chimie organique', 'Organic chemistry'), 'hexagon', 'orange'],
  [51, 'microbiologie', t('Microbiologie', 'Microbiology'), 'bug', 'lime', {
    units: [unit(23, t('Bactériologie générale', 'General bacteriology'), [
      course(32, 'paroi-bacterienne', t('Paroi bactérienne et coloration de Gram', 'Bacterial cell wall and Gram stain')),
    ])],
  }],
  [52, 'physiologie', t('Physiologie', 'Physiology'), 'activity', 'teal'],
  [53, 'botanique-medicinale', t('Botanique médicinale', 'Medicinal botany'), 'leaf', 'emerald'],
  [54, 'biophysique', t('Biophysique', 'Biophysics'), 'atom', 'sky'],
]);

export const CURRICULUM: readonly CurriculumModule[] = [
  ...medicineL1,
  ...medicineL2,
  ...dentistryL1,
  ...dentistryL2,
  ...pharmacyL1,
  ...pharmacyL2,
];
